#!/bin/bash

DIR=/sys/class/fc_host

echo "======================================================="
for DEV in $(ls -1 $DIR); do
   echo -e "Device: $DEV\n\tWWN: $(cat $DIR/$DEV/port_name)\tSpeed: $(cat $DIR/$DEV/speed)\tStatus: $(cat $DIR/$DEV/port_state)\n"
   echo "======================================================="
done
